export const users = [
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Lucas Almeida",
    position: "Desenvolvedor Front-end",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Carla Nogueira",
    position: "Designer Gráfico",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Rafael Costa",
    position: "Product Manager",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Marta Silva",
    position: "Engenheira de Software",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Ricardo Fernandes",
    position: "Desenvolvedor Back-end",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Larissa Oliveira",
    position: "Analista de Dados",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Fernando Santos",
    position: "Arquiteto de Soluções",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Priscila Souza",
    position: "Coordenadora de Projetos",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Carlos Moreira",
    position: "Administrador de Sistemas",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: true,
    name: "Bianca Lima",
    position: "Gerente de TI",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Juliana Pereira",
    position: "Analista de Suporte",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "André Ribeiro",
    position: "Desenvolvedor Full Stack",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Ana Martins",
    position: "UX Researcher",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Eduardo Silva",
    position: "Engenheiro de Infraestrutura",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Patrícia Gonçalves",
    position: "QA Tester",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Bruno Carvalho",
    position: "Analista de Sistemas",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Mariana Almeida",
    position: "Especialista em Segurança",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Rodrigo Fernandes",
    position: "Engenheiro de DevOps",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Letícia Costa",
    position: "Scrum Master",
  },
  {
    imgURL: "https://github.com/shadcn.png",
    online: false,
    name: "Gustavo Lima",
    position: "Analista de Negócios",
  },
];
